version: "3"

http:
  
  address: 0.0.0.0:8081

  max_request_size: 256

  middleware: ["static", "headers", "gzip"]

  uploads:
  
    dir: "/app/public"

    forbid: [".php", ".sh"]

  headers:
    
    response:
      X-Powered-By: "RoadRunner"

  static:
    
    dir: "/app/public"

    forbid: [".env", ".php"]

    response:
      X-Powered-By: "RoadRunner"


  pool:
    
    num_workers: 0

    max_jobs: 64

    supervisor:
     
      max_worker_memory: 128

      exec_ttl: 60s

  http2:

    h2c: false

    max_concurrent_streams: 128